### ISSUE TITLE
Installation failure due to wrong iipyper installation path?

### ISSUE THREAD

**Issue by YichenWangs** [Intelligent-Instruments-Lab/notochord#1]
Hello there!

Just want to make a note here that I found a small error when trying to install notochord.

It seems the iipyper directory is missing in the repo (specified in pyproject.toml) and evokes below error when installing:

```
Processing /private/var/folders/2z/c8nx_d8n7mlfq33dzjwb3qh00000gn/T/pip-install-pmo8__36/iipyper (from notochord)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/private/var/folders/2z/c8nx_d8n7mlfq33dzjwb3qh00000gn/T/pip-install-pmo8__36/iipyper'
```

My work-around solution was having the iipyper manually installed under the same directory with notochord and the issue was fixed :)

**Update**

See @cpmpercussion for fix via poetry.

Hope this helps,
Yichen

**Comment by victor-shepardson** [comment]
Hey, I updated the PyPI version and the README. You should be able to install simply with `pip install notochord`, or see https://github.com/Intelligent-Instruments-Lab/iil-dev/tree/main for developer instructions!
